from agent_basic import InteractionState

class MimicUser:
    def __init__(self, persona, task_requirement_gold):
        self.persona = persona
        self.task_requirement_gold = task_requirement_gold

    def respond(self, state: InteractionState):
        """
        Simulates the user feedback loop.
        """
        # In a real setup, an LLM would look at state['ground_truth'] 
        # and answer the agent's last question.
        messages = state["messages"]
        # Mock feedback based on ground truth
        feedback = f"Here is some user feedback generated by referring to persona & task_requirement_gold"
        # Update messages
        messages.append({"role": "user_feedback", "content": feedback})
        return messages