from agent_basic import InteractionState
import logging
import json
from jinja2 import Environment, FileSystemLoader

logger = logging.getLogger(__name__)


class MimicUser:
    def __init__(self, args):
        self.persona = persona  
        self.task_requirement_gold = task_requirement_gold
        self.user_instruction_init = user_instruction_init
        # Initialize Jinja2 Environment
        self.env = Environment(loader=FileSystemLoader(args.prompt_template_path))
        self.prompt_template_user_feedback = self.env.get_template(args.prompt_template_user_feedback_path)

    def respond(self, state: InteractionState):
        """
        Simulates the user feedback loop.
        """
        # In a real setup, an LLM would look at state['ground_truth'] 
        # and answer the agent's last question.
        messages = state["messages"]
        # Mock feedback based on ground truth

        template_vars = {
            "user_profile": self.persona,
            "init_user_instruction": self.user_instruction_init,
            "gold_task_requirement": self.task_requirement_gold,
            "aunu_question": last_assistant_msg
        }
        rendered_prompt = self.template.render(template_vars)

        # Send this rendered prompt to LLM and get feedback

        feedback = f"Here is some user feedback generated by referring to persona & task_requirement_gold"
        # Update messages
        message = {"role": "user_feedback", "content": feedback}
        logger.info({json.dumps(message)})
        messages.append(messages)
        #How should I log this message?
        return messages